services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: screen_server
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    ports:
      - "3306:3306"
    networks:
      - appnet
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: screen-back
    restart: unless-stopped
    expose:
      - 9000
    networks:
      - appnet
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./backend:/var/www
      - vendor:/var/www/vendor
    depends_on:
      - mysql

  frontend:
    container_name: screen-front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    networks:
      - appnet
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    restart: unless-stopped
    depends_on:
      - backend

  centrifugo:
    image: centrifugo/centrifugo:v5
    container_name: centrifugo
    restart: unless-stopped
    expose:
      - 8000
    networks:
      - appnet
    volumes:
      - ./centrifugo:/centrifugo
    command: centrifugo --config=/centrifugo/config.json --admin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - appnet
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootsecret
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
      - centrifugo
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  vendor:
  mysql_data:
  node_modules:
